version: "3.8"
services: 
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: task-management
      MYSQL_USER: sa
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root